// Auto-generated
let project = new Project('TestAnim');

project.addSources('Sources');
project.addLibrary("C:/Armory/armsdk/armory");
project.addLibrary("C:/Armory/armsdk/iron");
project.addLibrary("C:/Armory/armsdk/lib/haxebullet");
project.addAssets("C:/Armory/armsdk/lib/haxebullet/js/ammo/ammo.js", { notinlist: true });
project.addParameter('arm.Player');
project.addParameter("--macro keep('arm.Player')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Axe_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Axe_mesh.vert.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Axe_shadowmap.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Axe_shadowmap.vert.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Girl_armskin_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Girl_armskin_mesh.vert.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Girl_armskin_shadowmap.vert.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Ground_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Ground_mesh.vert.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Ground_shadowmap.vert.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_001_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_002_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_005_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_006_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_007_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_008_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_009_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_armskin_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_mesh.vert.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Road_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Tree2_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Wall1_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/armdefault_mesh.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/armdefault_mesh.vert.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/world_pass.frag.glsl");
project.addShaders("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/world_pass.vert.glsl");
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Axe_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Girl_armskin_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Ground_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_001_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_002_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_005_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_006_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_007_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_008_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_009_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_armskin_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Material_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Road_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Tree2_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/Wall1_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/armdefault_data.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Shaders/shader_datas.arm", { notinlist: true });
project.addAssets("Assets/Axe.png", { notinlist: true });
project.addAssets("Assets/Bear.png", { notinlist: true });
project.addAssets("Assets/Dog2.png", { notinlist: true });
project.addAssets("Assets/Girl5.png", { notinlist: true });
project.addAssets("Assets/House.png", { notinlist: true });
project.addAssets("Assets/Rock.png", { notinlist: true });
project.addAssets("Assets/Rock2.png", { notinlist: true });
project.addAssets("Assets/Tree.png", { notinlist: true });
project.addAssets("Assets/Tree3.png", { notinlist: true });
project.addAssets("Assets/Tree4.png", { notinlist: true });
project.addAssets("Assets/Wall1.png", { notinlist: true });
project.addAssets("Assets/Well.png", { notinlist: true });
project.addAssets("C:/Armory/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("C:/Armory/armsdk/armory/Assets/noise256.png", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/Scene.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/envmaps/World_irradiance.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/action_Armature.001_TreeAnimation.001.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/action_Armature.001_armorypose.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/action_Armature.002_Idle.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/action_Armature.002_Strike.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/action_Armature.002_Walk.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/action_Armature.002_armorypose.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/action_Armature_TreeAnimation.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/action_Armature_armorypose.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Axe.001.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Bear.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Cube.001.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Cube.002.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Dog2.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Girl5.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_House.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Plane.002.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Rock.002.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Rock.003.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Rock2.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree.002.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree.007.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree.008.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree.009.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree.010.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree.013.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree.014.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree.015.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree.016.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree3.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree4.007.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree4.008.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree4.009.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree4.010.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree4.011.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree4.017.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree4.018.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Tree4.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Wall1.003.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Wall1.004.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Wall1.005.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Wall1.arm", { notinlist: true });
project.addAssets("C:/Workspace/FarmDefence/build_FarmDefence/compiled/Assets/meshes/mesh_Well.arm", { notinlist: true });
project.addDefine('rp_renderer=Forward');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_size=1024');
project.addDefine('rp_background=World');
project.addDefine('rp_gi=Off');
project.addDefine('rp_ssgi=Off');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_shaderload');
project.addDefine('arm_soundcompress');
project.addDefine('arm_skin');
project.addDefine('arm_particles_gpu');
project.addDefine('arm_particles');
project.addDefine('arm_fast');


resolve(project);
