// Generated by Haxe 4.0.0-preview.4+6e012c1
#ifndef INCLUDED_iron_data_TMaterialContext
#define INCLUDED_iron_data_TMaterialContext

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(iron,data,TBindConstant)
HX_DECLARE_CLASS2(iron,data,TBindTexture)
HX_DECLARE_CLASS2(iron,data,TMaterialContext)

namespace iron{
namespace data{


class HXCPP_CLASS_ATTRIBUTES TMaterialContext_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef TMaterialContext_obj OBJ_;
		TMaterialContext_obj();

	public:
		enum { _hx_ClassId = 0x12e6d986 };

		void __construct(::String name,::Array< ::Dynamic> bind_constants,::Array< ::Dynamic> bind_textures);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="iron.data.TMaterialContext")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,true,"iron.data.TMaterialContext"); }
		static hx::ObjectPtr< TMaterialContext_obj > __new(::String name,::Array< ::Dynamic> bind_constants,::Array< ::Dynamic> bind_textures);
		static hx::ObjectPtr< TMaterialContext_obj > __alloc(hx::Ctx *_hx_ctx,::String name,::Array< ::Dynamic> bind_constants,::Array< ::Dynamic> bind_textures);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~TMaterialContext_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("TMaterialContext",14,da,08,b2); }

		::String name;
		::Array< ::Dynamic> bind_constants;
		::Array< ::Dynamic> bind_textures;
};

} // end namespace iron
} // end namespace data

#endif /* INCLUDED_iron_data_TMaterialContext */ 
