// Generated by Haxe 4.0.0-preview.4+6e012c1
#ifndef INCLUDED_iron_data_TMeshData
#define INCLUDED_iron_data_TMeshData

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(iron,data,TIndexArray)
HX_DECLARE_CLASS2(iron,data,TMeshData)
HX_DECLARE_CLASS2(iron,data,TSkin)
HX_DECLARE_CLASS2(iron,data,TVertexArray)
HX_DECLARE_CLASS2(kha,arrays,Float32ArrayPrivate)

namespace iron{
namespace data{


class HXCPP_CLASS_ATTRIBUTES TMeshData_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef TMeshData_obj OBJ_;
		TMeshData_obj();

	public:
		enum { _hx_ClassId = 0x545597b1 };

		void __construct(::String name,::Array< ::Dynamic> vertex_arrays,::Array< ::Dynamic> index_arrays, ::Dynamic dynamic_usage, ::iron::data::TSkin skin, ::kha::arrays::Float32ArrayPrivate instanced_data, ::Dynamic instanced_type,::String sdf_ref);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="iron.data.TMeshData")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,true,"iron.data.TMeshData"); }
		static hx::ObjectPtr< TMeshData_obj > __new(::String name,::Array< ::Dynamic> vertex_arrays,::Array< ::Dynamic> index_arrays, ::Dynamic dynamic_usage, ::iron::data::TSkin skin, ::kha::arrays::Float32ArrayPrivate instanced_data, ::Dynamic instanced_type,::String sdf_ref);
		static hx::ObjectPtr< TMeshData_obj > __alloc(hx::Ctx *_hx_ctx,::String name,::Array< ::Dynamic> vertex_arrays,::Array< ::Dynamic> index_arrays, ::Dynamic dynamic_usage, ::iron::data::TSkin skin, ::kha::arrays::Float32ArrayPrivate instanced_data, ::Dynamic instanced_type,::String sdf_ref);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~TMeshData_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("TMeshData",2b,f7,4d,dd); }

		::String name;
		::Array< ::Dynamic> vertex_arrays;
		::Array< ::Dynamic> index_arrays;
		 ::Dynamic dynamic_usage;
		 ::iron::data::TSkin skin;
		 ::kha::arrays::Float32ArrayPrivate instanced_data;
		 ::Dynamic instanced_type;
		::String sdf_ref;
};

} // end namespace iron
} // end namespace data

#endif /* INCLUDED_iron_data_TMeshData */ 
