// Generated by Haxe 4.0.0-preview.4+6e012c1
#ifndef INCLUDED_iron_data_TParticleReference
#define INCLUDED_iron_data_TParticleReference

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_6c6a258d838a2341_425_new)
HX_DECLARE_CLASS2(iron,data,TParticleReference)

namespace iron{
namespace data{


class HXCPP_CLASS_ATTRIBUTES TParticleReference_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef TParticleReference_obj OBJ_;
		TParticleReference_obj();

	public:
		enum { _hx_ClassId = 0x118e11a3 };

		void __construct(::String name,::String particle,int seed);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="iron.data.TParticleReference")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,true,"iron.data.TParticleReference"); }

		hx::ObjectPtr< TParticleReference_obj > __new(::String name,::String particle,int seed) {
			hx::ObjectPtr< TParticleReference_obj > __this = new TParticleReference_obj();
			__this->__construct(name,particle,seed);
			return __this;
		}

		static hx::ObjectPtr< TParticleReference_obj > __alloc(hx::Ctx *_hx_ctx,::String name,::String particle,int seed) {
			TParticleReference_obj *__this = (TParticleReference_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(TParticleReference_obj), true, "iron.data.TParticleReference"));
			*(void **)__this = TParticleReference_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_6c6a258d838a2341_425_new)
HXDLIN( 425)		( ( ::iron::data::TParticleReference)(__this) )->name = name;
HXDLIN( 425)		( ( ::iron::data::TParticleReference)(__this) )->particle = particle;
HXDLIN( 425)		( ( ::iron::data::TParticleReference)(__this) )->seed = seed;
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~TParticleReference_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("TParticleReference",b1,d1,9b,3d); }

		::String name;
		::String particle;
		int seed;
};

} // end namespace iron
} // end namespace data

#endif /* INCLUDED_iron_data_TParticleReference */ 
