// Generated by Haxe 4.0.0-preview.4+6e012c1
#ifndef INCLUDED_iron_data_TTilesheetData
#define INCLUDED_iron_data_TTilesheetData

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(iron,data,TTilesheetAction)
HX_DECLARE_CLASS2(iron,data,TTilesheetData)

namespace iron{
namespace data{


class HXCPP_CLASS_ATTRIBUTES TTilesheetData_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef TTilesheetData_obj OBJ_;
		TTilesheetData_obj();

	public:
		enum { _hx_ClassId = 0x14956441 };

		void __construct(::String name,int tilesx,int tilesy,int framerate,::Array< ::Dynamic> actions);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="iron.data.TTilesheetData")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,true,"iron.data.TTilesheetData"); }
		static hx::ObjectPtr< TTilesheetData_obj > __new(::String name,int tilesx,int tilesy,int framerate,::Array< ::Dynamic> actions);
		static hx::ObjectPtr< TTilesheetData_obj > __alloc(hx::Ctx *_hx_ctx,::String name,int tilesx,int tilesy,int framerate,::Array< ::Dynamic> actions);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~TTilesheetData_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("TTilesheetData",87,aa,6e,b7); }

		::String name;
		int tilesx;
		int tilesy;
		int framerate;
		::Array< ::Dynamic> actions;
};

} // end namespace iron
} // end namespace data

#endif /* INCLUDED_iron_data_TTilesheetData */ 
