// Generated by Haxe 4.0.0-preview.4+6e012c1
#ifndef INCLUDED_iron_data_TWorldData
#define INCLUDED_iron_data_TWorldData

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(iron,data,TProbe)
HX_DECLARE_CLASS2(iron,data,TWorldData)
HX_DECLARE_CLASS2(kha,arrays,Float32ArrayPrivate)

namespace iron{
namespace data{


class HXCPP_CLASS_ATTRIBUTES TWorldData_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef TWorldData_obj OBJ_;
		TWorldData_obj();

	public:
		enum { _hx_ClassId = 0x08c060f2 };

		void __construct(::String name,int background_color,::Array< ::Dynamic> probes, ::kha::arrays::Float32ArrayPrivate sun_direction, ::Dynamic turbidity, ::Dynamic ground_albedo,::String envmap);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="iron.data.TWorldData")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,true,"iron.data.TWorldData"); }
		static hx::ObjectPtr< TWorldData_obj > __new(::String name,int background_color,::Array< ::Dynamic> probes, ::kha::arrays::Float32ArrayPrivate sun_direction, ::Dynamic turbidity, ::Dynamic ground_albedo,::String envmap);
		static hx::ObjectPtr< TWorldData_obj > __alloc(hx::Ctx *_hx_ctx,::String name,int background_color,::Array< ::Dynamic> probes, ::kha::arrays::Float32ArrayPrivate sun_direction, ::Dynamic turbidity, ::Dynamic ground_albedo,::String envmap);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~TWorldData_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("TWorldData",a8,de,c1,09); }

		::String name;
		int background_color;
		::Array< ::Dynamic> probes;
		 ::kha::arrays::Float32ArrayPrivate sun_direction;
		 ::Dynamic turbidity;
		 ::Dynamic ground_albedo;
		::String envmap;
};

} // end namespace iron
} // end namespace data

#endif /* INCLUDED_iron_data_TWorldData */ 
