// Generated by Haxe 4.0.0-preview.4+6e012c1
#include <hxcpp.h>

#ifndef INCLUDED_haxe_io_Bytes
#include <hxinc/haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_kha_network_Client
#include <hxinc/kha/network/Client.h>
#endif

namespace kha{
namespace network{


static ::String Client_obj_sMemberFields[] = {
	HX_("get_id",24,f3,2f,a3),
	HX_("id",db,5b,00,00),
	HX_("send",48,8d,50,4c),
	HX_("receive",e3,61,58,2a),
	HX_("onClose",19,b6,a0,de),
	::String(null()) };

hx::Class Client_obj::__mClass;

void Client_obj::__register()
{
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_("kha.network.Client",35,53,75,ee);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mMembers = hx::Class_obj::dupFunctions(Client_obj_sMemberFields);
	__mClass->mCanCast = hx::TIsInterface< (int)0xe7ca9475 >;
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace kha
} // end namespace network
