// Generated by Haxe 4.0.0-preview.4+6e012c1
#include <hxcpp.h>

#ifndef INCLUDED_iron_data_TBindConstant
#include <hxinc/iron/data/TBindConstant.h>
#endif
#ifndef INCLUDED_iron_data_TBindTexture
#include <hxinc/iron/data/TBindTexture.h>
#endif
#ifndef INCLUDED_iron_data_TMaterialContext
#include <hxinc/iron/data/TMaterialContext.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_8e4aff4e6949e949_149_new,"iron.data.TMaterialContext","new",0x731faf24,"iron.data.TMaterialContext.new","iron/data/SceneFormat.hx",149,0x98b03519)
namespace iron{
namespace data{

void TMaterialContext_obj::__construct(::String name,::Array< ::Dynamic> bind_constants,::Array< ::Dynamic> bind_textures){
            	HX_STACKFRAME(&_hx_pos_8e4aff4e6949e949_149_new)
HXDLIN( 149)		this->name = name;
HXDLIN( 149)		this->bind_constants = bind_constants;
HXDLIN( 149)		this->bind_textures = bind_textures;
            	}

Dynamic TMaterialContext_obj::__CreateEmpty() { return new TMaterialContext_obj; }

void *TMaterialContext_obj::_hx_vtable = 0;

Dynamic TMaterialContext_obj::__Create(hx::DynamicArray inArgs)
{
	hx::ObjectPtr< TMaterialContext_obj > _hx_result = new TMaterialContext_obj();
	_hx_result->__construct(inArgs[0],inArgs[1],inArgs[2]);
	return _hx_result;
}

bool TMaterialContext_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x12e6d986;
}


hx::ObjectPtr< TMaterialContext_obj > TMaterialContext_obj::__new(::String name,::Array< ::Dynamic> bind_constants,::Array< ::Dynamic> bind_textures) {
	hx::ObjectPtr< TMaterialContext_obj > __this = new TMaterialContext_obj();
	__this->__construct(name,bind_constants,bind_textures);
	return __this;
}

hx::ObjectPtr< TMaterialContext_obj > TMaterialContext_obj::__alloc(hx::Ctx *_hx_ctx,::String name,::Array< ::Dynamic> bind_constants,::Array< ::Dynamic> bind_textures) {
	TMaterialContext_obj *__this = (TMaterialContext_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(TMaterialContext_obj), true, "iron.data.TMaterialContext"));
	*(void **)__this = TMaterialContext_obj::_hx_vtable;
	__this->__construct(name,bind_constants,bind_textures);
	return __this;
}

TMaterialContext_obj::TMaterialContext_obj()
{
}

void TMaterialContext_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(TMaterialContext);
	HX_MARK_MEMBER_NAME(name,"name");
	HX_MARK_MEMBER_NAME(bind_constants,"bind_constants");
	HX_MARK_MEMBER_NAME(bind_textures,"bind_textures");
	HX_MARK_END_CLASS();
}

void TMaterialContext_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(name,"name");
	HX_VISIT_MEMBER_NAME(bind_constants,"bind_constants");
	HX_VISIT_MEMBER_NAME(bind_textures,"bind_textures");
}

hx::Val TMaterialContext_obj::__Field(const ::String &inName,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"name") ) { return hx::Val( name ); }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"bind_textures") ) { return hx::Val( bind_textures ); }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"bind_constants") ) { return hx::Val( bind_constants ); }
	}
	return super::__Field(inName,inCallProp);
}

hx::Val TMaterialContext_obj::__SetField(const ::String &inName,const hx::Val &inValue,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"name") ) { name=inValue.Cast< ::String >(); return inValue; }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"bind_textures") ) { bind_textures=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"bind_constants") ) { bind_constants=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void TMaterialContext_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("name",4b,72,ff,48));
	outFields->push(HX_("bind_constants",4d,56,7e,59));
	outFields->push(HX_("bind_textures",3a,d9,41,d5));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static hx::StorageInfo TMaterialContext_obj_sMemberStorageInfo[] = {
	{hx::fsString,(int)offsetof(TMaterialContext_obj,name),HX_("name",4b,72,ff,48)},
	{hx::fsObject /*Array< ::Dynamic >*/ ,(int)offsetof(TMaterialContext_obj,bind_constants),HX_("bind_constants",4d,56,7e,59)},
	{hx::fsObject /*Array< ::Dynamic >*/ ,(int)offsetof(TMaterialContext_obj,bind_textures),HX_("bind_textures",3a,d9,41,d5)},
	{ hx::fsUnknown, 0, null()}
};
static hx::StaticInfo *TMaterialContext_obj_sStaticStorageInfo = 0;
#endif

static ::String TMaterialContext_obj_sMemberFields[] = {
	HX_("name",4b,72,ff,48),
	HX_("bind_constants",4d,56,7e,59),
	HX_("bind_textures",3a,d9,41,d5),
	::String(null()) };

hx::Class TMaterialContext_obj::__mClass;

void TMaterialContext_obj::__register()
{
	TMaterialContext_obj _hx_dummy;
	TMaterialContext_obj::_hx_vtable = *(void **)&_hx_dummy;
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_("iron.data.TMaterialContext",32,8d,90,82);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = hx::Class_obj::dupFunctions(TMaterialContext_obj_sMemberFields);
	__mClass->mCanCast = hx::TCanCast< TMaterialContext_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = TMaterialContext_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = TMaterialContext_obj_sStaticStorageInfo;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace iron
} // end namespace data
