// Generated by Haxe 4.0.0-preview.4+6e012c1
#include <hxcpp.h>

#ifndef INCLUDED_iron_App
#include <hxinc/iron/App.h>
#endif
#ifndef INCLUDED_iron_Trait
#include <hxinc/iron/Trait.h>
#endif
#ifndef INCLUDED_iron_object_Object
#include <hxinc/iron/object/Object.h>
#endif
#ifndef INCLUDED_kha_graphics2_Graphics
#include <hxinc/kha/graphics2/Graphics.h>
#endif
#ifndef INCLUDED_kha_graphics4_Graphics
#include <hxinc/kha/graphics4/Graphics.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_5_new,"iron.Trait","new",0xadc250fa,"iron.Trait.new","iron/Trait.hx",5,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_26_remove,"iron.Trait","remove",0xf0f4f7ea,"iron.Trait.remove","iron/Trait.hx",26,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_29_notifyOnAdd,"iron.Trait","notifyOnAdd",0xe8630d53,"iron.Trait.notifyOnAdd","iron/Trait.hx",29,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_34_notifyOnInit,"iron.Trait","notifyOnInit",0x7399eb9e,"iron.Trait.notifyOnInit","iron/Trait.hx",34,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_40_notifyOnRemove,"iron.Trait","notifyOnRemove",0x6bdf0c52,"iron.Trait.notifyOnRemove","iron/Trait.hx",40,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_45_notifyOnUpdate,"iron.Trait","notifyOnUpdate",0xee5bf617,"iron.Trait.notifyOnUpdate","iron/Trait.hx",45,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_51_removeUpdate,"iron.Trait","removeUpdate",0x13c0bd93,"iron.Trait.removeUpdate","iron/Trait.hx",51,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_56_notifyOnLateUpdate,"iron.Trait","notifyOnLateUpdate",0xd63b74dd,"iron.Trait.notifyOnLateUpdate","iron/Trait.hx",56,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_62_removeLateUpdate,"iron.Trait","removeLateUpdate",0xa0bfaa59,"iron.Trait.removeLateUpdate","iron/Trait.hx",62,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_67_notifyOnRender,"iron.Trait","notifyOnRender",0x6c7fdb64,"iron.Trait.notifyOnRender","iron/Trait.hx",67,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_73_removeRender,"iron.Trait","removeRender",0x91e4a2e0,"iron.Trait.removeRender","iron/Trait.hx",73,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_78_notifyOnRender2D,"iron.Trait","notifyOnRender2D",0x70b8a836,"iron.Trait.notifyOnRender2D","iron/Trait.hx",78,0xf191d4b7)
HX_LOCAL_STACK_FRAME(_hx_pos_a97bb283ec9ba9b9_84_removeRender2D,"iron.Trait","removeRender2D",0x4e7b46b2,"iron.Trait.removeRender2D","iron/Trait.hx",84,0xf191d4b7)
namespace iron{

void Trait_obj::__construct(){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_5_new)
HXLINE(  19)		this->_render2D = null();
HXLINE(  18)		this->_render = null();
HXLINE(  17)		this->_lateUpdate = null();
HXLINE(  16)		this->_update = null();
HXLINE(  15)		this->_remove = null();
HXLINE(  14)		this->_init = null();
HXLINE(  13)		this->_add = null();
HXLINE(   7)		this->name = HX_("",00,00,00,00);
            	}

Dynamic Trait_obj::__CreateEmpty() { return new Trait_obj; }

void *Trait_obj::_hx_vtable = 0;

Dynamic Trait_obj::__Create(hx::DynamicArray inArgs)
{
	hx::ObjectPtr< Trait_obj > _hx_result = new Trait_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Trait_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x7b609ac2;
}

void Trait_obj::remove(){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_26_remove)
HXDLIN(  26)		this->object->removeTrait(hx::ObjectPtr<OBJ_>(this));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Trait_obj,remove,(void))

void Trait_obj::notifyOnAdd( ::Dynamic f){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_29_notifyOnAdd)
HXLINE(  30)		if (hx::IsNull( this->_add )) {
HXLINE(  30)			this->_add = ::Array_obj< ::Dynamic>::__new(0);
            		}
HXLINE(  31)		this->_add->push(f);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Trait_obj,notifyOnAdd,(void))

void Trait_obj::notifyOnInit( ::Dynamic f){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_34_notifyOnInit)
HXLINE(  35)		if (hx::IsNull( this->_init )) {
HXLINE(  35)			this->_init = ::Array_obj< ::Dynamic>::__new(0);
            		}
HXLINE(  36)		this->_init->push(f);
HXLINE(  37)		::iron::App_obj::notifyOnInit(f);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Trait_obj,notifyOnInit,(void))

void Trait_obj::notifyOnRemove( ::Dynamic f){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_40_notifyOnRemove)
HXLINE(  41)		if (hx::IsNull( this->_remove )) {
HXLINE(  41)			this->_remove = ::Array_obj< ::Dynamic>::__new(0);
            		}
HXLINE(  42)		this->_remove->push(f);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Trait_obj,notifyOnRemove,(void))

void Trait_obj::notifyOnUpdate( ::Dynamic f){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_45_notifyOnUpdate)
HXLINE(  46)		if (hx::IsNull( this->_update )) {
HXLINE(  46)			this->_update = ::Array_obj< ::Dynamic>::__new(0);
            		}
HXLINE(  47)		this->_update->push(f);
HXLINE(  48)		::iron::App_obj::notifyOnUpdate(f);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Trait_obj,notifyOnUpdate,(void))

void Trait_obj::removeUpdate( ::Dynamic f){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_51_removeUpdate)
HXLINE(  52)		this->_update->remove(f);
HXLINE(  53)		::iron::App_obj::removeUpdate(f);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Trait_obj,removeUpdate,(void))

void Trait_obj::notifyOnLateUpdate( ::Dynamic f){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_56_notifyOnLateUpdate)
HXLINE(  57)		if (hx::IsNull( this->_lateUpdate )) {
HXLINE(  57)			this->_lateUpdate = ::Array_obj< ::Dynamic>::__new(0);
            		}
HXLINE(  58)		this->_lateUpdate->push(f);
HXLINE(  59)		::iron::App_obj::notifyOnLateUpdate(f);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Trait_obj,notifyOnLateUpdate,(void))

void Trait_obj::removeLateUpdate( ::Dynamic f){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_62_removeLateUpdate)
HXLINE(  63)		this->_lateUpdate->remove(f);
HXLINE(  64)		::iron::App_obj::removeLateUpdate(f);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Trait_obj,removeLateUpdate,(void))

void Trait_obj::notifyOnRender( ::Dynamic f){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_67_notifyOnRender)
HXLINE(  68)		if (hx::IsNull( this->_render )) {
HXLINE(  68)			this->_render = ::Array_obj< ::Dynamic>::__new(0);
            		}
HXLINE(  69)		this->_render->push(f);
HXLINE(  70)		::iron::App_obj::notifyOnRender(f);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Trait_obj,notifyOnRender,(void))

void Trait_obj::removeRender( ::Dynamic f){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_73_removeRender)
HXLINE(  74)		this->_render->remove(f);
HXLINE(  75)		::iron::App_obj::removeRender(f);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Trait_obj,removeRender,(void))

void Trait_obj::notifyOnRender2D( ::Dynamic f){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_78_notifyOnRender2D)
HXLINE(  79)		if (hx::IsNull( this->_render2D )) {
HXLINE(  79)			this->_render2D = ::Array_obj< ::Dynamic>::__new(0);
            		}
HXLINE(  80)		this->_render2D->push(f);
HXLINE(  81)		::iron::App_obj::notifyOnRender2D(f);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Trait_obj,notifyOnRender2D,(void))

void Trait_obj::removeRender2D( ::Dynamic f){
            	HX_STACKFRAME(&_hx_pos_a97bb283ec9ba9b9_84_removeRender2D)
HXLINE(  85)		this->_render2D->remove(f);
HXLINE(  86)		::iron::App_obj::removeRender2D(f);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Trait_obj,removeRender2D,(void))


hx::ObjectPtr< Trait_obj > Trait_obj::__new() {
	hx::ObjectPtr< Trait_obj > __this = new Trait_obj();
	__this->__construct();
	return __this;
}

hx::ObjectPtr< Trait_obj > Trait_obj::__alloc(hx::Ctx *_hx_ctx) {
	Trait_obj *__this = (Trait_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(Trait_obj), true, "iron.Trait"));
	*(void **)__this = Trait_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

Trait_obj::Trait_obj()
{
}

void Trait_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Trait);
	HX_MARK_MEMBER_NAME(name,"name");
	HX_MARK_MEMBER_NAME(object,"object");
	HX_MARK_MEMBER_NAME(_add,"_add");
	HX_MARK_MEMBER_NAME(_init,"_init");
	HX_MARK_MEMBER_NAME(_remove,"_remove");
	HX_MARK_MEMBER_NAME(_update,"_update");
	HX_MARK_MEMBER_NAME(_lateUpdate,"_lateUpdate");
	HX_MARK_MEMBER_NAME(_render,"_render");
	HX_MARK_MEMBER_NAME(_render2D,"_render2D");
	HX_MARK_END_CLASS();
}

void Trait_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(name,"name");
	HX_VISIT_MEMBER_NAME(object,"object");
	HX_VISIT_MEMBER_NAME(_add,"_add");
	HX_VISIT_MEMBER_NAME(_init,"_init");
	HX_VISIT_MEMBER_NAME(_remove,"_remove");
	HX_VISIT_MEMBER_NAME(_update,"_update");
	HX_VISIT_MEMBER_NAME(_lateUpdate,"_lateUpdate");
	HX_VISIT_MEMBER_NAME(_render,"_render");
	HX_VISIT_MEMBER_NAME(_render2D,"_render2D");
}

hx::Val Trait_obj::__Field(const ::String &inName,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"name") ) { return hx::Val( name ); }
		if (HX_FIELD_EQ(inName,"_add") ) { return hx::Val( _add ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"_init") ) { return hx::Val( _init ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"object") ) { return hx::Val( object ); }
		if (HX_FIELD_EQ(inName,"remove") ) { return hx::Val( remove_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"_remove") ) { return hx::Val( _remove ); }
		if (HX_FIELD_EQ(inName,"_update") ) { return hx::Val( _update ); }
		if (HX_FIELD_EQ(inName,"_render") ) { return hx::Val( _render ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"_render2D") ) { return hx::Val( _render2D ); }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"_lateUpdate") ) { return hx::Val( _lateUpdate ); }
		if (HX_FIELD_EQ(inName,"notifyOnAdd") ) { return hx::Val( notifyOnAdd_dyn() ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"notifyOnInit") ) { return hx::Val( notifyOnInit_dyn() ); }
		if (HX_FIELD_EQ(inName,"removeUpdate") ) { return hx::Val( removeUpdate_dyn() ); }
		if (HX_FIELD_EQ(inName,"removeRender") ) { return hx::Val( removeRender_dyn() ); }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"notifyOnRemove") ) { return hx::Val( notifyOnRemove_dyn() ); }
		if (HX_FIELD_EQ(inName,"notifyOnUpdate") ) { return hx::Val( notifyOnUpdate_dyn() ); }
		if (HX_FIELD_EQ(inName,"notifyOnRender") ) { return hx::Val( notifyOnRender_dyn() ); }
		if (HX_FIELD_EQ(inName,"removeRender2D") ) { return hx::Val( removeRender2D_dyn() ); }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"removeLateUpdate") ) { return hx::Val( removeLateUpdate_dyn() ); }
		if (HX_FIELD_EQ(inName,"notifyOnRender2D") ) { return hx::Val( notifyOnRender2D_dyn() ); }
		break;
	case 18:
		if (HX_FIELD_EQ(inName,"notifyOnLateUpdate") ) { return hx::Val( notifyOnLateUpdate_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

hx::Val Trait_obj::__SetField(const ::String &inName,const hx::Val &inValue,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"name") ) { name=inValue.Cast< ::String >(); return inValue; }
		if (HX_FIELD_EQ(inName,"_add") ) { _add=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"_init") ) { _init=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"object") ) { object=inValue.Cast<  ::iron::object::Object >(); return inValue; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"_remove") ) { _remove=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		if (HX_FIELD_EQ(inName,"_update") ) { _update=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		if (HX_FIELD_EQ(inName,"_render") ) { _render=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"_render2D") ) { _render2D=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"_lateUpdate") ) { _lateUpdate=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Trait_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("name",4b,72,ff,48));
	outFields->push(HX_("object",bf,7e,3f,15));
	outFields->push(HX_("_add",22,37,15,3f));
	outFields->push(HX_("_init",ef,56,cc,f8));
	outFields->push(HX_("_remove",e3,ad,ff,72));
	outFields->push(HX_("_update",a8,97,7c,f5));
	outFields->push(HX_("_lateUpdate",ee,b2,da,ed));
	outFields->push(HX_("_render",f5,7c,a0,73));
	outFields->push(HX_("_render2D",07,90,71,fa));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static hx::StorageInfo Trait_obj_sMemberStorageInfo[] = {
	{hx::fsString,(int)offsetof(Trait_obj,name),HX_("name",4b,72,ff,48)},
	{hx::fsObject /*::iron::object::Object*/ ,(int)offsetof(Trait_obj,object),HX_("object",bf,7e,3f,15)},
	{hx::fsObject /*cpp::ArrayBase*/ ,(int)offsetof(Trait_obj,_add),HX_("_add",22,37,15,3f)},
	{hx::fsObject /*cpp::ArrayBase*/ ,(int)offsetof(Trait_obj,_init),HX_("_init",ef,56,cc,f8)},
	{hx::fsObject /*cpp::ArrayBase*/ ,(int)offsetof(Trait_obj,_remove),HX_("_remove",e3,ad,ff,72)},
	{hx::fsObject /*cpp::ArrayBase*/ ,(int)offsetof(Trait_obj,_update),HX_("_update",a8,97,7c,f5)},
	{hx::fsObject /*cpp::ArrayBase*/ ,(int)offsetof(Trait_obj,_lateUpdate),HX_("_lateUpdate",ee,b2,da,ed)},
	{hx::fsObject /*cpp::ArrayBase*/ ,(int)offsetof(Trait_obj,_render),HX_("_render",f5,7c,a0,73)},
	{hx::fsObject /*cpp::ArrayBase*/ ,(int)offsetof(Trait_obj,_render2D),HX_("_render2D",07,90,71,fa)},
	{ hx::fsUnknown, 0, null()}
};
static hx::StaticInfo *Trait_obj_sStaticStorageInfo = 0;
#endif

static ::String Trait_obj_sMemberFields[] = {
	HX_("name",4b,72,ff,48),
	HX_("object",bf,7e,3f,15),
	HX_("_add",22,37,15,3f),
	HX_("_init",ef,56,cc,f8),
	HX_("_remove",e3,ad,ff,72),
	HX_("_update",a8,97,7c,f5),
	HX_("_lateUpdate",ee,b2,da,ed),
	HX_("_render",f5,7c,a0,73),
	HX_("_render2D",07,90,71,fa),
	HX_("remove",44,9c,88,04),
	HX_("notifyOnAdd",b9,62,3b,83),
	HX_("notifyOnInit",78,4f,0c,56),
	HX_("notifyOnRemove",ac,9a,95,9a),
	HX_("notifyOnUpdate",71,84,12,1d),
	HX_("removeUpdate",6d,21,33,f6),
	HX_("notifyOnLateUpdate",37,38,61,50),
	HX_("removeLateUpdate",33,03,fa,d4),
	HX_("notifyOnRender",be,69,36,9b),
	HX_("removeRender",ba,06,57,74),
	HX_("notifyOnRender2D",10,01,f3,a4),
	HX_("removeRender2D",0c,d5,31,7d),
	::String(null()) };

hx::Class Trait_obj::__mClass;

void Trait_obj::__register()
{
	Trait_obj _hx_dummy;
	Trait_obj::_hx_vtable = *(void **)&_hx_dummy;
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_("iron.Trait",08,0c,dc,86);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = hx::Class_obj::dupFunctions(Trait_obj_sMemberFields);
	__mClass->mCanCast = hx::TCanCast< Trait_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Trait_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Trait_obj_sStaticStorageInfo;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace iron
